void Delay();
bit Soft_I2c_Get_Ack();
void Soft_I2c_Ack();
void Soft_I2c_Nak();
void I2C_Init();
void I2C_Start();
bit I2C_Get_Ack();
bit I2C_Write(unsigned char dat);
void I2C_Ack();
void I2C_Nak();
unsigned char I2C_Read(bit ack);
void I2C_Stop();
void DS1307_Write(unsigned char add, unsigned char dat);
unsigned char DS1307_Read(unsigned char add);
void DS1307_Init();
bit DS1307_Read_Time(unsigned int * hour, unsigned int * minute, unsigned int * second);
void DS1307_Write_Time(unsigned char hour, unsigned char minute, unsigned char second);
void DS1307_Read_Date(unsigned int * day, unsigned int * date, unsigned int * month, unsigned int * year);
void DS1307_Write_Date(unsigned char day, unsigned char date, unsigned char month, unsigned char year);
void DS1307_Write_Bytes(unsigned char add, unsigned char * buff,	unsigned char len);
void DS137_Read_Bytes(unsigned char add,unsigned char * buff, unsigned char len);